<script lang="ts">
	import { mfaLabels } from '$lib/auth/client';
	import { Admonition } from '$lib/components';

	const { data } = $props();

	const mfaKind = data.desiredMFA;
	const action = data.action;
</script>

{#if action === 'register'}
	{#if mfaKind === 'passkeys'}
		<div class="space-y-8 rounded-card p-8 shadow-3">
			<h2 class="t-base-lg font-medium">Step 2: Select Passkey</h2>
			<Admonition kind="info" title="You will be able to choose a device to use as your passkey."></Admonition>
		</div>
	{/if}

	{#if mfaKind === 'authenticator'}
		<div class="space-y-8 rounded-card p-8 shadow-3">
			<h2 class="t-base-lg font-medium">Step 2: Add To Authenticator App</h2>
			<Admonition kind="info" title="A QR Code will be generated for your application."></Admonition>
		</div>

		<div class="space-y-8 rounded-card p-8 shadow-3">
			<h2 class="t-base-lg font-medium">Step 3: Verify Authenticator Code</h2>
			<Admonition kind="info" title="Enter the 6-digit code generated by the app."></Admonition>
		</div>
	{/if}

	{#if mfaKind === 'sms'}
		<div class="space-y-8 rounded-card p-8 shadow-3">
			<h2 class="t-base-lg font-medium">Step 2: Enter Phone Number</h2>
			<Admonition kind="info" title="A code will be sent to your phone number."></Admonition>
		</div>

		<div class="space-y-8 rounded-card p-8 shadow-3">
			<h2 class="t-base-lg font-medium">Step 3: Verify SMS Code</h2>
			<Admonition kind="info" title="Enter the 6-digit code sent to your phone."></Admonition>
		</div>
	{/if}
{/if}

{#if action === 'remove'}
	<div class="space-y-8 rounded-card p-8 shadow-3">
		<h2 class="t-base-lg font-medium">Step 2: Confirm {mfaLabels[mfaKind]} MFA Deletion</h2>
		<button class="btn btn-error" disabled>Confirm</button>
	</div>
{/if}
